#!/usr/bin/env bash

# If KERNEL_INSTALL_INITRD_GENERATOR is set, disable this hook
[[ -n "$KERNEL_INSTALL_INITRD_GENERATOR" ]] && exit 0

DRACUT_UEFI=$(
    [[ -f "/etc/dracut.conf" ]] && . "/etc/dracut.conf" 2>/dev/null
	if [[ -d "/etc/dracut.conf.d" ]]; then
		for f in /etc/dracut.conf.d/*.conf; do
			[[ -f "$f" ]] && . "$f" 2>/dev/null
    	done
	fi
	[[ "$uefi" == "yes" ]] && echo true || echo false
)

if [[ "$DRACUT_UEFI" == true ]]; then
	if [[ ! -d "/sys/firmware/efi" ]]; then
        echo "Warning: Dracut configured for UKI (uefi=yes), but /sys/firmware/efi not found. If you are in a chroot, ensure the host booted in UEFI mode." >&2
    fi
		
	ESP=$(
		for p in "/efi" "/boot/efi" "/boot"; do
			mountpoint -q "$p" && { echo "$p"; break; }
		done
	)
	[[ -z "$ESP" ]] && echo "Error: ESP partition is not mounted. (Checked at /efi, /boot/efi and /boot.)" >&2 && exit 1
	[[ "$ESP" == "/boot/efi" ]] && echo "Warning: ESP mounted at /boot/efi. Prefer /efi or /boot." >&2
fi

dracut_build() {
    local pkgbase=$1
    local kver=$2
	local args=('--force' '-L 3')
    
	install -Dm0644 "/usr/lib/modules/${kver}/vmlinuz" "/boot/vmlinuz-${pkgbase}"

	case "$DRACUT_UEFI" in 
 		true)
			mkdir -p "${ESP}/EFI/Linux"
			echo "--> Building UKI for ${pkgbase} (${kver})"
			dracut "${args[@]}" "${ESP}/EFI/Linux/arch-${pkgbase}.efi" --kver "$kver"
			;;

		false)
			echo "--> Building initramfs for ${pkgbase} (${kver})"
			dracut "${args[@]}" "/boot/initramfs-${pkgbase}.img" --kver "$kver"
			;;
	esac
}

# Use associative array to collect kernels and avoid duplicate builds
declare -A kernels_for_build
build_all=false

while read -r line; do
	[[ "$build_all" = true ]] && continue

	case "$line" in
    	'usr/lib/modules/'*'/pkgbase')
        	kver="${line#'usr/lib/modules/'}"
        	kver="${kver%'/pkgbase'}"

			kernels_for_build["$kver"]=1
        	;;

		'usr/lib/firmware/'*'/'   | \
		'usr/src/'*'/dkms.conf'   | \
		'usr/lib/systemd/systemd' | \
		'usr/bin/cryptsetup'	  | \
		'usr/bin/lvm' 		      | \
		'usr/lib/dracut/'*'/')          	
			build_all=true
        	;;
	esac	
done

# If a common dependency was updated, mark all installed kernels for build
if [[ "$build_all" == true ]]; then
    for kernel in /usr/lib/modules/*/; do
        if [[ -f "${kernel}/pkgbase" ]]; then
            kver="${kernel%/}"
            kver="${kver##*/}"
            kernels_for_build["$kver"]=1
        fi
    done
fi

# Finally, execute builds ONLY ONCE per kernel
for kver in "${!kernels_for_build[@]}"; do
    if [[ -f "/usr/lib/modules/${kver}/pkgbase" ]]; then
        read -r pkgbase < "/usr/lib/modules/${kver}/pkgbase"
        dracut_build "$pkgbase" "$kver"
    fi
done
